# Generated by Django 4.2.6 on 2023-11-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estruturashabitacionais_a_igreja_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacaoaggfamiliar',
            name='codigo_igreja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='identificacaoaggfamiliar',
            name='codigo_machamba',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
